import ImgUpload from "@/components/ImgUpload"
import Head from "next/head"
import styled from "styled-components"


const DIV = styled.div`
    margin: 80px auto;
    text-align: center;
    .uploader_wrap{
        width: 60%;
        min-width: 200px;
        max-width: 900px;
        padding: 10px;
        margin: auto;
        border: 2px dashed gray;
        border-radius: 6px;
    }
`

export default function ImgSource () {
    return(<>
        <Head>
            <title>延迟图床</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <DIV>
                <ImgUpload className="uploader_wrap">
                    <div>ImgSource</div>
                </ImgUpload>
            </DIV>
        </main>
    </>)
}