import LazyImage from '@/components/LazyImage'
import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'

const DIV = styled.div`
  &.wrap{
    width: fit-content;
    margin: 10vh auto;
    text-align: center;
  }
  .img{
    max-width: 100%;
  }
  .back{
    display: block;
    text-shadow: 0 0 10px gray;
    font-weight: bold;
    font-size: 6vh;
    color: #fff
  }
`

export default function Error() {
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DIV className='wrap'>
          <LazyImage className='img' src='https://miro.medium.com/v2/resize:fit:1400/1*zE2qnVTJehut7B8P2aMn3A.gif' />
          <Link href="/" className='back' aria-label="back to homepage">BACK</Link>
        </DIV>
      </main>
    </>
  )
}
