import { editArtical, listArtical } from '@/req/main'
import { Artical } from '@/types/global'
import Head from 'next/head'
import { useState } from 'react'
import BlogCreator from '../components/creator'

type Props = {
  artical: Artical
}

export default function BlogEdit({ artical: defaultArtical }: Props) {
  const [artical] = useState<Artical>(defaultArtical)
  return (
    <>
      <Head>
        <title>edit blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BlogCreator artical={artical} onSubmit={editArtical} />
      </main>
    </>
  )
}



export const getServerSideProps = async (context: any) => {
  const { number } = context.query
  const props: Partial<Props> = {}
  if (+String(number) + 1) {
    const res = await listArtical(number);
    if (res?.data) {
      props.artical = res.data
    }
  }
  return { props }
}
