import ImgUpload from "@/components/ImgUpload"
import SVGIcon from "@/components/SVGIcon"
import Head from "next/head"
import styled from "styled-components"


const DIV = styled.div`
    margin: 80px auto;
    text-align: center;
    .uploader_wrap{
        width: 60%;
        min-width: 200px;
        max-width: 900px;
        padding: 10px;
        margin: auto;
        border: 2px dashed gray;
        border-radius: 6px;
        cursor: pointer;
    }
    .tips{
        font-size: 0.8em;
        color: gray;
    }
    @media (max-width: 769px) {
        .uploader_wrap{
            width: 90%;
        }
    }
`

export default function ImgSource() {
    return (<>
        <Head>
            <title>延迟图床</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <DIV>
                <ImgUpload className="uploader_wrap">
                    <div>
                        <SVGIcon width="32" style={{ fill: 'gray' }} type="plus_no_outline" />
                    </div>
                    <span className="tips">图片最大不超过3m</span>
                </ImgUpload>
            </DIV>
        </main>
    </>)
}